name=input("enter the name")
print("the name is",name)
a=name.isalpha()
print(a)
b=name.isalnum()
print(b)
c=name.isdigit()
print(c)
d=name.islower()
print(d)
e=name.isupper()
print(e)
f=name.isspace()
print(f)
g=name.istitle()
print(g)
